# Generated by Django 6.0.5 on 2026-05-14 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('resident_type', models.CharField(choices=[('owner', 'Propietario'), ('tenant', 'Inquilino')], default='tenant', max_length=20, verbose_name='Tipo de residente')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='Usado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='units.apartment', verbose_name='Apartamento')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invitado por')),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('resident_type', models.CharField(choices=[('owner', 'Propietario'), ('tenant', 'Inquilino')], default='tenant', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='Estado')),
                ('move_in_date', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('move_out_date', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='residents/', verbose_name='Foto')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, verbose_name='Contacto de emergencia')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de emergencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='units.apartment', verbose_name='Apartamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
