# Generated by Django 6.0.5 on 2026-05-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='apartment',
        ),
        migrations.AddField(
            model_name='resident',
            name='apartments',
            field=models.ManyToManyField(blank=True, related_name='residents', to='units.apartment', verbose_name='Apartamentos'),
        ),
    ]
