# Generated by Django 6.0.5 on 2026-05-14 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('towers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('floor', models.PositiveIntegerField(verbose_name='Piso')),
                ('status', models.CharField(choices=[('occupied', 'Ocupado'), ('vacant', 'Vacante'), ('maintenance', 'En mantenimiento')], default='vacant', max_length=20, verbose_name='Estado')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área (m²)')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cuota mensual')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='towers.tower', verbose_name='Torre')),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
                'ordering': ['tower', 'floor', 'number'],
                'unique_together': {('tower', 'number')},
            },
        ),
    ]
