# Generated by Django 6.0.5 on 2026-05-15 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='status',
        ),
    ]
