# Generated by Django 6.0.5 on 2026-05-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('maintenance', 'Mantenimiento'), ('extra', 'Extraordinaria'), ('other', 'Otro')], default='maintenance', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('submitted', 'En revisión'), ('paid', 'Pagado'), ('overdue', 'Vencido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
