# Generated by Django 6.0.5 on 2026-05-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment_type_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='payments/receipts/', verbose_name='Comprobante'),
        ),
    ]
