# Generated by Django 6.0.5 on 2026-05-14 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(choices=[('plumbing', 'Plomería'), ('electrical', 'Eléctrico'), ('elevator', 'Elevador'), ('common_areas', 'Áreas comunes'), ('security', 'Seguridad'), ('noise', 'Ruido'), ('cleaning', 'Limpieza'), ('structural', 'Estructura'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Categoría')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En proceso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='open', max_length=20, verbose_name='Estado')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='issues/', verbose_name='Foto')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del administrador')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='units.apartment', verbose_name='Apartamento')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='residents.resident', verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
    ]
