# Generated by Django 6.0.5 on 2026-05-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issuenote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='admin_notes',
        ),
    ]
