# Generated by Django 6.0.5 on 2026-05-15 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_remove_issue_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='issues.issue', verbose_name='Duplicado de'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En proceso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado'), ('duplicated', 'Duplicado')], default='open', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='issuenote',
            name='status',
            field=models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En proceso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado'), ('duplicated', 'Duplicado')], max_length=20, verbose_name='Estado'),
        ),
    ]
