# Generated by Django 6.0.5 on 2026-05-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_payments_enabled', models.BooleanField(default=False, verbose_name='Generar pagos automáticamente')),
                ('payment_due_day', models.PositiveSmallIntegerField(default=10, help_text='Día del mes en que vencen los pagos (1-28).', verbose_name='Día de vencimiento')),
                ('payment_type', models.CharField(choices=[('maintenance', 'Mantenimiento'), ('extra', 'Extraordinaria'), ('other', 'Otro')], default='maintenance', max_length=20, verbose_name='Tipo de pago')),
                ('overdue_check_enabled', models.BooleanField(default=False, verbose_name='Marcar pagos vencidos automáticamente')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
            },
        ),
    ]
