# Generated by Django 6.0.5 on 2026-05-15 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
        ('towers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowerMaintenanceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cuota de mantenimiento')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_fee', to='towers.tower', verbose_name='Torre')),
            ],
            options={
                'verbose_name': 'Cuota de mantenimiento',
                'verbose_name_plural': 'Cuotas de mantenimiento',
                'ordering': ['tower__name'],
            },
        ),
    ]
