# Generated by Django 6.0.5 on 2026-05-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_add_tower_maintenance_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='company_address',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre de la empresa'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='company_rfc',
            field=models.CharField(blank=True, max_length=50, verbose_name='RFC / NIT / Identificador fiscal'),
        ),
    ]
